//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Korisnici.ClientLibrary.WebServices.AccountsService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Login", Namespace="http://schemas.datacontract.org/2004/07/Korsinici.Web.Models")]
    [System.SerializableAttribute()]
    public partial class Login : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdKorisnikaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImeIPrezimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KorisnickoImeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LogIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdKorisnika {
            get {
                return this.IdKorisnikaField;
            }
            set {
                if ((this.IdKorisnikaField.Equals(value) != true)) {
                    this.IdKorisnikaField = value;
                    this.RaisePropertyChanged("IdKorisnika");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImeIPrezime {
            get {
                return this.ImeIPrezimeField;
            }
            set {
                if ((object.ReferenceEquals(this.ImeIPrezimeField, value) != true)) {
                    this.ImeIPrezimeField = value;
                    this.RaisePropertyChanged("ImeIPrezime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KorisnickoIme {
            get {
                return this.KorisnickoImeField;
            }
            set {
                if ((object.ReferenceEquals(this.KorisnickoImeField, value) != true)) {
                    this.KorisnickoImeField = value;
                    this.RaisePropertyChanged("KorisnickoIme");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LogId {
            get {
                return this.LogIdField;
            }
            set {
                if ((this.LogIdField.Equals(value) != true)) {
                    this.LogIdField = value;
                    this.RaisePropertyChanged("LogId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusMessage {
            get {
                return this.StatusMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusMessageField, value) != true)) {
                    this.StatusMessageField = value;
                    this.RaisePropertyChanged("StatusMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Entity", Namespace="http://schemas.datacontract.org/2004/07/rs.mvc.Korisnici.Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Korisnici.ClientLibrary.WebServices.AccountsService.Aplikacija))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Korisnici.ClientLibrary.WebServices.AccountsService.Korisnik))]
    public partial class Entity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AktivanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Aktivan {
            get {
                return this.AktivanField;
            }
            set {
                if ((this.AktivanField.Equals(value) != true)) {
                    this.AktivanField = value;
                    this.RaisePropertyChanged("Aktivan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Aplikacija", Namespace="http://schemas.datacontract.org/2004/07/rs.mvc.Korisnici.Model")]
    [System.SerializableAttribute()]
    public partial class Aplikacija : Korisnici.ClientLibrary.WebServices.AccountsService.Entity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DomainField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HomeUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Korisnici.ClientLibrary.WebServices.AccountsService.Korisnik[] KorisniciField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazivField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Domain {
            get {
                return this.DomainField;
            }
            set {
                if ((object.ReferenceEquals(this.DomainField, value) != true)) {
                    this.DomainField = value;
                    this.RaisePropertyChanged("Domain");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HomeUrl {
            get {
                return this.HomeUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.HomeUrlField, value) != true)) {
                    this.HomeUrlField = value;
                    this.RaisePropertyChanged("HomeUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Kod {
            get {
                return this.KodField;
            }
            set {
                if ((object.ReferenceEquals(this.KodField, value) != true)) {
                    this.KodField = value;
                    this.RaisePropertyChanged("Kod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Korisnici.ClientLibrary.WebServices.AccountsService.Korisnik[] Korisnici {
            get {
                return this.KorisniciField;
            }
            set {
                if ((object.ReferenceEquals(this.KorisniciField, value) != true)) {
                    this.KorisniciField = value;
                    this.RaisePropertyChanged("Korisnici");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Logo {
            get {
                return this.LogoField;
            }
            set {
                if ((object.ReferenceEquals(this.LogoField, value) != true)) {
                    this.LogoField = value;
                    this.RaisePropertyChanged("Logo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Naziv {
            get {
                return this.NazivField;
            }
            set {
                if ((object.ReferenceEquals(this.NazivField, value) != true)) {
                    this.NazivField = value;
                    this.RaisePropertyChanged("Naziv");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Korisnik", Namespace="http://schemas.datacontract.org/2004/07/rs.mvc.Korisnici.Model")]
    [System.SerializableAttribute()]
    public partial class Korisnik : Korisnici.ClientLibrary.WebServices.AccountsService.Entity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AdministratorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Korisnici.ClientLibrary.WebServices.AccountsService.Aplikacija[] AplikacijeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KorisnickoImeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] LozinkaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LozinkaPlainField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrezimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TemporaryPasswordField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Administrator {
            get {
                return this.AdministratorField;
            }
            set {
                if ((this.AdministratorField.Equals(value) != true)) {
                    this.AdministratorField = value;
                    this.RaisePropertyChanged("Administrator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Korisnici.ClientLibrary.WebServices.AccountsService.Aplikacija[] Aplikacije {
            get {
                return this.AplikacijeField;
            }
            set {
                if ((object.ReferenceEquals(this.AplikacijeField, value) != true)) {
                    this.AplikacijeField = value;
                    this.RaisePropertyChanged("Aplikacije");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMail {
            get {
                return this.EMailField;
            }
            set {
                if ((object.ReferenceEquals(this.EMailField, value) != true)) {
                    this.EMailField = value;
                    this.RaisePropertyChanged("EMail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ime {
            get {
                return this.ImeField;
            }
            set {
                if ((object.ReferenceEquals(this.ImeField, value) != true)) {
                    this.ImeField = value;
                    this.RaisePropertyChanged("Ime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KorisnickoIme {
            get {
                return this.KorisnickoImeField;
            }
            set {
                if ((object.ReferenceEquals(this.KorisnickoImeField, value) != true)) {
                    this.KorisnickoImeField = value;
                    this.RaisePropertyChanged("KorisnickoIme");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Lozinka {
            get {
                return this.LozinkaField;
            }
            set {
                if ((object.ReferenceEquals(this.LozinkaField, value) != true)) {
                    this.LozinkaField = value;
                    this.RaisePropertyChanged("Lozinka");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LozinkaPlain {
            get {
                return this.LozinkaPlainField;
            }
            set {
                if ((object.ReferenceEquals(this.LozinkaPlainField, value) != true)) {
                    this.LozinkaPlainField = value;
                    this.RaisePropertyChanged("LozinkaPlain");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prezime {
            get {
                return this.PrezimeField;
            }
            set {
                if ((object.ReferenceEquals(this.PrezimeField, value) != true)) {
                    this.PrezimeField = value;
                    this.RaisePropertyChanged("Prezime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TemporaryPassword {
            get {
                return this.TemporaryPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.TemporaryPasswordField, value) != true)) {
                    this.TemporaryPasswordField = value;
                    this.RaisePropertyChanged("TemporaryPassword");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebServices.AccountsService.AccountsService")]
    public interface AccountsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AccountsService/Login", ReplyAction="http://tempuri.org/AccountsService/LoginResponse")]
        Korisnici.ClientLibrary.WebServices.AccountsService.Login Login(string username, string password, string appCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AccountsService/Logout", ReplyAction="http://tempuri.org/AccountsService/LogoutResponse")]
        void Logout(int logId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AccountsService/GetUserInfo", ReplyAction="http://tempuri.org/AccountsService/GetUserInfoResponse")]
        Korisnici.ClientLibrary.WebServices.AccountsService.Korisnik GetUserInfo(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AccountsService/Save", ReplyAction="http://tempuri.org/AccountsService/SaveResponse")]
        void Save(Korisnici.ClientLibrary.WebServices.AccountsService.Korisnik korisnik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AccountsService/ChangePassword", ReplyAction="http://tempuri.org/AccountsService/ChangePasswordResponse")]
        void ChangePassword(int userid, string newPassword);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AccountsServiceChannel : Korisnici.ClientLibrary.WebServices.AccountsService.AccountsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccountsServiceClient : System.ServiceModel.ClientBase<Korisnici.ClientLibrary.WebServices.AccountsService.AccountsService>, Korisnici.ClientLibrary.WebServices.AccountsService.AccountsService {
        
        public AccountsServiceClient() {
        }
        
        public AccountsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccountsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Korisnici.ClientLibrary.WebServices.AccountsService.Login Login(string username, string password, string appCode) {
            return base.Channel.Login(username, password, appCode);
        }
        
        public void Logout(int logId) {
            base.Channel.Logout(logId);
        }
        
        public Korisnici.ClientLibrary.WebServices.AccountsService.Korisnik GetUserInfo(int id) {
            return base.Channel.GetUserInfo(id);
        }
        
        public void Save(Korisnici.ClientLibrary.WebServices.AccountsService.Korisnik korisnik) {
            base.Channel.Save(korisnik);
        }
        
        public void ChangePassword(int userid, string newPassword) {
            base.Channel.ChangePassword(userid, newPassword);
        }
    }
}
